Bug 1272068 - use tags to distinguish different apps in Sentry
mozilla/ichnaea pull request #1320
Opened 2020-09-11 17:23 UTC by djmitche

Not actually tested with Sentry itself, but this seems to pass CI tests.

2020-09-11 17:24 UTC, djmitche commented
Fixes #988.

2020-09-11 21:19 UTC, jwhitlock requested changes
Thanks @djmitche! I was able to test this with the stage DSN,

```
make shell
SENTRY_DSN=https://<etc> ichnaea/scripts/sentry_test.py clitest
```

In Sentry, the tags are:

* level: error
* node: sentry_test
* release: unknown
* server_name: 59e3c4bbdec4

I think I'd prefer `app` or `app_type` to `node`, but it is not a strong preference.

Can you run ``make lintfix`` to get black happy, and rebase on the current main branch?

2020-09-11 21:41 UTC, djmitche commented on ichnaea/log.py
> +def configure_raven(transport=None, tags={}, _client=None):
Yeah, good point.  My python's a little rusty (heh) and I forgot about that issue.  And I will eventually learn to remember lint!

2020-09-14 16:21 UTC, jwhitlock approved these changes
Tested as before, now app=sentry_test. Thanks @djmitche, looks good!

2020-09-14 16:21 UTC, merged