get rid of more  null mccs list from countries.json
mozilla/ichnaea pull request #1469
Opened 2020-12-21 10:03 UTC by szjozsef

Please review and if you consider, then merge this pull request.
Unfortunately It contains some hard-coded values, for country codes which otherwise can't really be obtained by data parsing.
For Cocos Islands and Christmas Island I edited also the Wikipedia page, but if that edit will get reverted for some reason, the included commit will parse the 
"includes
    Cocos Islands (Australia) – CC
    Christmas Island (Australia) – CX
"
list section, including the iso codes from there if they was not already included.
The second commit includes hard-coded iso codes.

2020-12-21 17:07 UTC, jwhitlock requested changes
Thanks @szjozsef, these look like good changes. There's a few changes needed before merging.

2020-12-22 08:21 UTC, szjozsef commented on mobile_codes/tests.py
> +        # operator_mccs.remove("995")
Done

2020-12-22 08:21 UTC, szjozsef commented on mobile_codes/tests.py
> +        assert len(countries) == 4
Done
(else: NF Norfolk Island)

2020-12-22 15:32 UTC, jwhitlock approved these changes
Thanks @szjozsef!

2020-12-22 15:32 UTC, merged